## kommunikativch metasfresh-db image version
## ref: https://cloud.docker.com/repository/docker/kommunikativch/metasfresh-db/tags
##
db:
  replicas: 1
  image:
    registry: docker.io
    repository: kommunikativch/metasfresh-db
    tag: "5.118"
    ## Specify a imagePullPolicy
    ## Defaults to 'Always' if image tag is 'latest', else set to 'IfNotPresent'
    ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
    ##
    pullPolicy: Always
    ## Optionally specify an array of imagePullSecrets.
    ## Secrets must be manually created in the namespace.
    ## ref: https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/
    ##
    pullSecrets:
      - kommunikativch-dockerhub

  podLabels: {}
  ## db resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  # resources:
  #   requests:
  #     memory: 256Mi
  #     cpu: 100m

  ## db Node labels and tolerations for pod assignment
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#nodeselector
  ## ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#taints-and-tolerations-beta-feature
  # nodeSelector: {"beta.kubernetes.io/arch": "amd64"}
  # tolerations: []
  ## metasfresh-db pod annotations
  podAnnotations: {}
  ## metasfresh-db Pod Security Context
  securityContext:
    enabled: true
    fsGroup: 1001
    runAsUser: 1001

  port: 5432
  persistence:
    enabled: true

    ## The path the volume will be mounted at, useful when using different
    ## metasfresh-db images.
    path: /var/lib/postgresql/data

    ## The subdirectory of the volume to mount to, useful in dev environments and one PV for multiple services.
    subPath: db/data

    ## db data Persistent Volume Storage Class
    ## If defined, storageClassName: <storageClass>
    ## If set to "-", storageClassName: "", which disables dynamic provisioning
    ## If undefined (the default) or set to null, no storageClassName spec is
    ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
    ##   GKE, AWS & OpenStack)
    ##
    storageClass: "storage-metasfresh-db"
    accessModes:
    - ReadWriteOnce
    size: 8Gi
    