apiVersion: v1
{{- if .Values.persistence.enabled }}      
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.dbData.volumeName }}
  labels:
    app: "{{ template "db.name" . }}"
    chart: {{ template "db.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
  - pdName: "disk-metasfresh-db-data-kommunikativ"
  - fsType: "ext-4"
  storageClassName: ""
{{- end }}
