apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-db-pvc
  labels:
    app: "{{ template "db.name" . }}"
    chart: {{ template "db.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  {{- if .Values.persistence.enabled }}      
  resources:
    requests:
      storage: "1Ki"
  volumeMode: Filesystem
  volumeName: {{ .Values.persistence.dbData.volumeName }}
  {{- else }}
  resources:
    requests:
      storage: {{ .Values.persistence.dbData.size }}
  {{- end }}
