apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{ .Values.db.persistence.volumeName }}
