apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "search.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "search.name" . }}
    chart: {{ template "search.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      release: "{{ .Release.Name }}"
      app: {{ template "search.name" . }}
  serviceName: "search"  
  template:
    metadata:
      labels:
        release: "{{ .Release.Name }}"
        app: {{ template "search.name" . }}
{{- if .Values.search.podLabels }}
{{ toYaml .Values.search.podLabels | indent 8 }}
{{- end }}
      {{- if .Values.search.podAnnotations }}
      annotations:
{{ toYaml .Values.search.podAnnotations | indent 8 }}
      {{- end }}
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "search"
      {{- if .Values.search.image.pullSecrets }}
      imagePullSecrets:
        {{- range .Values.search.image.pullSecrets }}
        - name: {{ . }}
        {{- end}}
      {{- end}}
      containers:
      {{- if not .Values.transfer.enabled }}
      - name: {{ template "search.fullname" . }}
        image: "{{ template "search.image" . }}"
        imagePullPolicy: {{ default "" .Values.search.image.pullPolicy | quote }}
        ports:
        - name: search
          containerPort: {{ .Values.search.port }}
        volumeMounts:
        - name: search-data
          mountPath: {{ .Values.search.persistence.searchData.path }}
          subPath: {{ .Release.Namespace }}/{{ .Values.search.persistence.searchData.subPath }}
        resources:
          limits:
            memory: 1Gi
            cpu: "200m"
          requests:
            memory: 1Gi
            cpu: "10m"
      {{- end}}
      {{- if .Values.transfer.enabled }}
      - name: "transfer"
        image: "{{ template "search.transfer.image" . }}"
        imagePullPolicy: {{ default "" .Values.search.transfer.image.pullPolicy | quote }}
        securityContext:
          allowPrivilegeEscalation: true
          capabilities:
            add:
              - SYS_ADMIN
          privileged: true
          readOnlyRootFilesystem: false
        stdin: true
        tty: true           
        volumeMounts:
        - name: search-data
          mountPath: /search-data
          subPath: {{ .Release.Namespace }}/{{ .Values.search.persistence.searchData.subPath }}
      {{- end}}
      volumes:
      - name: search-data
        persistentVolumeClaim:
          claimName: search-data-search-data-pvc
