name: metasfresh
version: 5.118
appVersion: 5.118
description: Open source, advanced key-value store. It is often referred to as a data structure server since keys can contain strings, hashes, lists, sets and sorted sets.
keywords:
- metasfresh
- erp
home: http://metasfresh.com/
icon: https://avatars0.githubusercontent.com/u/13364239?s=200&v=4
sources:
- https://https://github.com/metasfresh
maintainers:
- name: ??
  email: ??
engine: gotpl