apiVersion: v1
kind: Service
metadata:
  name: "app"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "app.name" . }}
    chart: {{ template "app.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: app
    port: 8282
    targetPort: app
  - name: portActiveMq
    port: 61616
    targetPort: portActiveMq
  selector:
    app: {{ template "app.name" . }}
    release: "{{ .Release.Name }}"
