apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-data-reports-pvc
  labels:
    app: "{{ template "app.name" . }}"
    chart: {{ template "app.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.persistence.enabled }}      
  resources:
    requests:
      storage: {{ .Values.persistence.reports.size  | quote }}
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{ .Values.persistence.reports.volumeName }}
{{- else }}
  resources:
    requests:
      storage: {{ .Values.persistence.reports.size }}
{{- end }}