apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-log-pvc
  labels:
    app: "{{ template "db.name" . }}"
    chart: {{ template "db.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
  - ReadWriteOnce
{{- if .Values.persistence.enabled }}      
  resources:
    requests:
      storage: {{ .Values.persistence.log.size  | quote }}
  storageClassName: ""
  volumeMode: Filesystem
  volumeName: {{ .Values.persistence.log.volumeName }}
{{- else }}
  resources:
    requests:
      storage: {{ .Values.persistence.log.size }}
{{- end }}