apiVersion: v1
kind: Service
metadata:
  name: "search"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "search.name" . }}
    chart: {{ template "search.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: search
    port: 9300
    targetPort: search
  selector:
    app: {{ template "search.name" . }}
    release: "{{ .Release.Name }}"
