apiVersion: v1
kind: Service
metadata:
  name: {{ template "metasfresh-db.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "metasfresh-db.name" . }}
    chart: {{ template "metasfresh-db.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"