apiVersion: v1
kind: Service
metadata:
  name: "webui"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "webui.name" . }}
    chart: {{ template "webui.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: http
    port: 80
    targetPort: http
  - name: https
    port: 443
    targetPort: https
  selector:
    app: {{ template "webui.name" . }}
    release: "{{ .Release.Name }}"
