apiVersion: v1
kind: Service
metadata:
  name: "webapi"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "webapi.name" . }}
    chart: {{ template "webapi.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: webapi
    port: 8080
    targetPort: webapi
  selector:
    app: {{ template "webapi.name" . }}
    release: "{{ .Release.Name }}"
