apiVersion: v1
kind: Service
metadata:
  name: "rabbitmq"
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "rabbitmq.name" . }}
    chart: {{ template "rabbitmq.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  ports:
  - name: rabbitmq
    port: 5672
    targetPort: rabbitmq
  selector:
    app: {{ template "rabbitmq.name" . }}
    release: "{{ .Release.Name }}"
