apiVersion: v1     
kind: PersistentVolume
metadata:
  name: {{ .Values.persistence.dbData.volumeName | "vol-metasfresh-db-data" }}
  labels:
    app: "{{ template "db.name" . }}"
    chart: {{ template "db.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  gcePersistentDisk:
    pdName: "disk-metasfresh-db-data-kommunikativ"
    fsType: "ext-4"
  storageClassName: ""
