{{- if .Values.persistence.transfer.enabled }} 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-data-transfer-pvc
  labels:
    app: "{{ template "db.name" . }}"
    chart: {{ template "db.chart" . }}
    release: {{ .Release.Name | quote }}
    heritage: {{ .Release.Service | quote }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.transfer.size }}
{{- end }}
